version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      args:
        - NODE_VERSION=20
    container_name: separate-tracks-api
    environment:
      - NODE_ENV=production
      - UPLOADS_DIR=/data/uploads
    volumes:
      - uploads_data:/data/uploads
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000/files').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - NODE_VERSION=20
        - VITE_API_URL=http://api:3000
    container_name: separate-tracks-web
    depends_on:
      - api
    ports:
      - "8080:80"

volumes:
  uploads_data:
